### ISSUE TITLE
Setup a basic flask server

### ISSUE THREAD

**Issue by rakaar** [rakaar/Movie-search-engine#6]
Create a `backend` folder and include a basic flask application boiler plate.

**Comment by aditya-hari** [comment]
What should this flask application be capable of doing?

**Comment by rakaar** [comment]
@aditya-hari , for now just a very basic one. like at '/' route sending hello world.
Later Iets add the functionality of receiving query from the frontend, once its ready.

**Comment by aditya-hari** [comment]
Alright, on it. Will get this done very soon
